# fly.toml app configuration file generated for zione-chatbot on 2023-10-14T21:54:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zione-chatbot"
primary_region = "bog"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
